module.exports = {
    apps:[
        {
            name:"Servidor1",
            script:"src/app.js",
            watch:true,
            env:{
                PORT:8080
            },
        },
        {
            name:"Servidor2",
            script:"src/app.js",
            watch:true,
            env:{
                PORT:8082
            },
            exec_mode:"cluster",
        },
        {
            name:"Servidor3",
            script:"src/app.js",
            watch:true,
            env:{
                PORT:8083
            },
            exec_mode:"cluster",
        },
        {
            name:"Servidor4",
            script:"src/app.js",
            watch:true,
            env:{
                PORT:8084
            },
            exec_mode:"cluster",
        },
        {
            name:"Servidor5",
            script:"src/app.js",
            watch:true,
            env:{
                PORT:8085
            },
            exec_mode:"cluster",
        }
    ]
}